# Configuración del servidor
server.port=8080
spring.application.name=ms-pedidos360-bff

# Configuración de validación de Token (Microsoft Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/1587de59-3259-4555-988c-2907c91e031c/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=07250aed-3169-4f84-aebf-a14b946a0807